### PR TITLE
Only send ping after sending pong response to nodes with invalid endpoint proofs

### PR DESCRIPTION
**Pull request by halfalicious**
Fix item 3 in #4959 

When receiving a ping from a node for which we've already completed the endpoint proof, don't send a ping in addition to the pong response. Note that prior to these changes, we wouldn't send a ping after the pong to nodes whose endpoint proofs had expired. 

I've also added a unit test which validates this behavior.

### CODE REVIEW

**Comment by halfalicious** [comment]
Rebased since the following test was failing and gumb0 checked in some changes which improve its stability:
```

The following tests FAILED:
	493 - network/net/noteActiveNodeReplacesNodeInFullBucketWhenEndpointChanged (Failed)
```

**Comment by halfalicious** [comment]
New test is failing: 
```

The following tests FAILED:
	505 - network/net/pingNotSentAfterPongForKnownNode (Failed)
```

Not failing locally so it's either a timing issue or something Linux-specific, once I can figure out how to re-run tests in circleci with increased TestEth verbosity I'll investigate.

File: libp2p/NodeTable.cpp [hunk 1]
```diff
@@ -102,34 +115,28 @@ bool NodeTable::addNode(Node const& _node, NodeRelation _relation)
...
-    }
+    // Log here to avoid holding the x_nodes mutex longer than necessary
+    if (bFound)
+        LOG(m_logger) << "Node " << _node.id << "@" << _node.endpoint
+                      << " is already in the node table";
+    else
+        LOG(m_logger) << "Pending node " << _node.id << "@" << _node.endpoint;
+
+    if (!newNodeEntry->hasValidEndpointProof())
+        ping(*newNodeEntry);
```
[the remark this answers is not in the document]
Comment (gumb0) [reply libp2p/NodeTable.cpp]: Other place is before sending `FindNode`

File: libp2p/NodeTable.h [hunk 2]
```diff
@@ -207,7 +207,8 @@ class NodeTable : UDPSocketEvents
         std::list<std::weak_ptr<NodeEntry>> nodes;
     };
 
-    /// Used ping known node. Used by node table when refreshing buckets and as part of eviction process (see evict).
+    /// Used ping known node. Used by node table when refreshing buckets and as part of eviction
```
Comment (gumb0) [inline libp2p/NodeTable.h]: Not sure I understand `Used ping known node.` is it a typo?

File: libp2p/NodeTable.cpp [hunk 3]
```diff
@@ -102,34 +115,28 @@ bool NodeTable::addNode(Node const& _node, NodeRelation _relation)
...
-        return false;
-    }
+    // Log here to avoid holding the x_nodes mutex longer than necessary
+    if (bFound)
+        LOG(m_logger) << "Node " << _node.id << "@" << _node.endpoint
+                      << " is already in the node table";
+    else
+        LOG(m_logger) << "Pending node " << _node.id << "@" << _node.endpoint;
+
+    if (!newNodeEntry->hasValidEndpointProof())
```
Comment (gumb0) [inline libp2p/NodeTable.cpp]: Maybe we also could simplify this function by removing `if (_relation == Known)` part, then adding ` && _relation != Known` on this line.
Then we'd also need to add
```
  if (_relation == Known)
     newNodeEntry->lastPongReceivedTime = RLPXDatagramFace::secondsSinceEpoch();
```

File: test/unittests/libp2p/net.cpp [hunk 4]
```diff
@@ -939,6 +940,85 @@ BOOST_AUTO_TEST_CASE(findNodeIsSentAfterPong)
...
+    // Validate 3 scenarios:
+    // * A ping is sent after a pong for a new node
+    // * No ping is sent after a pong for a known node with a valid endpoint proof
+    // * A ping is sent after a pong for a known node with an invalid endpoint proof
+
+    TestNodeTableHost nodeTableHost1(0);
+    nodeTableHost1.start();
+    auto& nodeTable1 = nodeTableHost1.nodeTable;
+
+    TestUDPSocketHost nodeSocketHost2{getRandomPortNumber()};
```
Comment (gumb0) [inline test/unittests/libp2p/net.cpp]: small test simplification suggestion: I guess port parameter to `TestUDPSocketHost` is not needed anymore, as we always pass random port there (so we can just move `getRandomPortNumber()` inside constructor)

File: test/unittests/libp2p/net.cpp [hunk 5]
```diff
@@ -939,6 +940,85 @@ BOOST_AUTO_TEST_CASE(findNodeIsSentAfterPong)
...
+    auto nodeKeyPair2 = KeyPair::create();
+    Node node2(nodeKeyPair2.pub(), nodeEndpoint2);
+    nodeTable1->addNode(node2);
+
+    // Verify ping is received
+    auto packetReceived1 = nodeSocketHost2.packetsReceived.pop(chrono::milliseconds(5000));
+    auto datagram1 =
+        DiscoveryDatagram::interpretUDP(bi::udp::endpoint{}, dev::ref(packetReceived1));
+    auto ping1 = dynamic_cast<PingNode const&>(*datagram1);
+    BOOST_CHECK_EQUAL(datagram1->typeName(), "Ping");
```
Comment (gumb0) [inline test/unittests/libp2p/net.cpp]: `dynamic_cast` above would throw anyway if it's not Ping

File: test/unittests/libp2p/net.cpp [hunk 6]
```diff
@@ -939,6 +940,85 @@ BOOST_AUTO_TEST_CASE(findNodeIsSentAfterPong)
...
+    BOOST_CHECK_EQUAL(datagram4->typeName(), "Pong");
+
+    // Verify that the next packet received is not a ping
+    auto packetReceived5 = nodeSocketHost2.packetsReceived.pop(chrono::milliseconds(20000));
+    auto datagram5 =
+        DiscoveryDatagram::interpretUDP(bi::udp::endpoint{}, dev::ref(packetReceived5));
+    BOOST_REQUIRE(datagram5->typeName() != "Ping");
+
+    // Force the endpoint proof to be invalid
+    shared_ptr<NodeEntry> newNode = nodeTable1->m_allNodes.begin()->second;
```
Comment (gumb0) [inline test/unittests/libp2p/net.cpp]: this is not thread-safe, can you use `nodeTable1->nodeEntry()` ?
(still would be not entirely safe as `lastPongReceivedTime` be accessed from another thread... but polluting the tests with perfect thread-safety seems too much of a hassle to me)

File: libp2p/NodeTable.cpp (hunk 3 above)
Comment (chfast) [reply libp2p/NodeTable.cpp]: Previously the case for `Known` was completely disjoint so I planned to move it to a separate function. Now it has some sanity check which are good to have so it is not so simple any more.

File: libp2p/NodeTable.h (hunk 2 above)
Comment (halfalicious) [reply libp2p/NodeTable.h]: Yea me neither, I think it’s a typo from a previous commit. Will change.

File: libp2p/NodeTable.cpp [hunk 7]
```diff
@@ -102,34 +115,28 @@ bool NodeTable::addNode(Node const& _node, NodeRelation _relation)
...
         auto const it = m_allNodes.find(_node.id);
         if (it != m_allNodes.end())
-        {
-            LOG(m_logger) << "Node " << _node.id << "@" << _node.endpoint
-                          << " is already in the node table";
-            return true;
-        }
+            bFound = true;
+        else
+            m_allNodes[_node.id] = make_shared<NodeEntry>(m_hostNodeID, _node.id, _node.endpoint);
```
[the remark this answers is not in the document]
Comment (halfalicious) [reply libp2p/NodeTable.cpp]: Didn't realize std::map had an insert function that did that, thanks for the tip!

File: libp2p/NodeTable.cpp [hunk 8]
```diff
@@ -102,34 +115,28 @@ bool NodeTable::addNode(Node const& _node, NodeRelation _relation)
...
 
-    if (!_node.endpoint || !_node.id)
-    {
-        LOG(m_logger) << "Supplied node has an invalid endpoint (" << _node.endpoint << ") or id ("
-                      << _node.id << "). Skipping adding to node table.";
-        return false;
-    }
-
+    bool bFound = false;
+    shared_ptr<NodeEntry> newNodeEntry = nullptr;
```
[the remark this answers is not in the document]
Comment (halfalicious) [reply libp2p/NodeTable.cpp]: Agreed, will change to `nodeEntry`

File: test/unittests/libp2p/net.cpp (hunk 5 above)
Comment (halfalicious) [reply test/unittests/libp2p/net.cpp]: Ah the line before the BOOST_CHECK_EQUAL is a copy/paste artifact. Thanks for catching this!

File: test/unittests/libp2p/net.cpp (hunk 4 above)
Comment (halfalicious) [reply test/unittests/libp2p/net.cpp]: I'll actually make the default value of the ctor's port parameter a call to getRandomPortNumber()...that way if we want to listen on a specific port for some reason we still can.

File: libp2p/NodeTable.cpp [hunk 9]
```diff
@@ -90,46 +90,50 @@ void NodeTable::processEvents()
...
     {
-        auto const it = m_allNodes.find(_node.id);
-        if (it != m_allNodes.end())
-        {
-            LOG(m_logger) << "Node " << _node.id << "@" << _node.endpoint
-                          << " is already in the node table";
-            return true;
-        }
+        auto nodePair = m_allNodes.insert(
+            {_node.id, make_shared<NodeEntry>(m_hostNodeID, _node.id, _node.endpoint)});
```
Comment (chfast) [inline libp2p/NodeTable.cpp]: This way you create a shared_ptr unnecessary when an entry is already in the table. That's you I asked to insert nullptr first which later can be replaced with correct shared_ptr if needed.

File: libp2p/NodeTable.cpp [hunk 10]
```diff
@@ -548,6 +551,9 @@ void NodeTable::onPacketReceived(
                     if (it != m_allNodes.end())
                         it->second->lastPongSentTime = RLPXDatagramFace::secondsSinceEpoch();
                 }
+                else
```
Comment (chfast) [inline libp2p/NodeTable.cpp]: Use "quick return" as suggested by @gumb0:
```
if (!addNode(...))
    return;

// Send PONG response
...
break;
```

File: libp2p/NodeTable.cpp [hunk 11]
```diff
@@ -90,46 +90,50 @@ void NodeTable::processEvents()
...
     }
 
+    if (m_hostNodeID == _node.id)
+    {
+        LOG(m_logger) << "Skip adding self to node table (" << _node.id << ")";
+        return false;
+    }
+
+    bool bFound = false;
+    std::shared_ptr<NodeEntry> nodeEntry = nullptr;
```
Comment (gumb0) [inline libp2p/NodeTable.cpp]: `= nullptr` is redundant

File: libp2p/NodeTable.cpp [hunk 12]
```diff
@@ -90,53 +90,53 @@ void NodeTable::processEvents()
...
+            bFound = true;
+        nodeEntry = iterPair.first->second;
     }
 
-    if (!isAllowedEndpoint(_node.endpoint))
+    // Log here to avoid holding the x_nodes mutex longer than necessary
+    if (bFound)
+        LOG(m_logger) << "Node " << _node.id << "@" << _node.endpoint
+                      << " is already in the node table";
+    else if (!bFound && _relation != Known)
```
Comment (gumb0) [inline libp2p/NodeTable.cpp]: Maybe simpler
```
    else
        LOG(m_logger) << (_relation == Known ? "Known : "Pending") << " node " << _node.id << "@" << _node.endpoint;
```

**Comment by halfalicious** [comment]
> 
> 
> A test is failing.

These tests are failing:
```

	493 - network/net/noteActiveNodeReplacesNodeInFullBucketWhenEndpointChanged (Failed)
	504 - network/net/addSelf (Failed)
```

Logs:
	
	```
487/558 Test #493: network/net/noteActiveNodeReplacesNodeInFullBucketWhenEndpointChanged .................................................***Failed    0.20 sec
Running tests using path: "/home/builder/project/test/jsontests"
Running 1 test case...
Test Case "noteActiveNodeReplacesNodeInFullBucketWhenEndpointChanged": 
/home/builder/project/test/unittests/libp2p/net.cpp(549): error: in "network/net/noteActiveNodeReplacesNodeInFullBucketWhenEndpointChanged": check mostRecentNodeEntry->endpoint == newEndpoint has failed [127.0.0.1 UDP 45917 TCP 45917 != 127.0.0.1 UDP 4954 TCP 4954]

*** 1 failure is detected (5 failures are expected) in the test module "Master Test Suite"
```

```
Running 1 test case...
Test Case "addSelf": 
/home/builder/project/test/unittests/libp2p/net.cpp(944): error: in "network/net/addSelf": check nodeTable->count() == ++expectedNodeCount - 1 has failed

*** 1 failure is detected (5 failures are expected) in the test module "Master Test Suite"
```

Will investigate tonight. @gumb0 : Are there any known issues with the first test?

**Comment by chfast** [comment]
There were some conflicts with https://github.com/ethereum/aleth/pull/5429. Maybe I have not resolved them correctly when rebasing.

**Comment by halfalicious** [comment]
> 
> 
> There were some conflicts with #5429. Maybe I have not resolved them correctly when rebasing.

Okay, will investigate tonight.

**Comment by halfalicious** [comment]
> 
> 
> > There were some conflicts with #5429. Maybe I have not resolved them correctly when rebasing.
> 
> Okay, will investigate tonight.

Fixed the test failures - the addSelf failure was due to bad rebase (the self check in addNode was removed) and the other failure was because we didn't update the node entry endpoint in addNode if the node was a known node.

**Comment by halfalicious** [comment]
Seeing a strange failure in the "Upload Coverage Data" stage of the linux-gcc6 run. Doubt it's related to my changes.

**Comment by gumb0** [comment]
I've been thinking about the case of the changed endpoint and its relation to the vulnerability https://github.com/ethereum/aleth/issues/5455, and now it seems to me that we handle it insecurely - currently if endpoint changes we continue to trust this node's endpoint proof without re-pinging it.

I think we should
- remove updating the endpoint from `noteActiveNode`, probably just remove `_endpoint` parameter. This function will assume that node's enpdoint is up-to-date.
- make `addNode` in case endpoint changes invalidate pong sent/received times (set to 0) and send another Ping

I'm fine with merging this PR like this and handling it in another PR.

**Comment by halfalicious** [comment]
> 
> 
> @chfast : Can you review and sign off please?

Actually, I see that you signed off but requested changes because of the failing tests. I've fixed the failures and gumb0 has reviewed them so I think it's okay to merge now.
